baseURL = 'https://cheztervargas.com/'
locale = "en"
title = "Chezter's Records"
uglyURLs = false
disableKinds = ["taxonomy", "term"]

[params]
  author = 'Chezter Vargas'

[permalinks]
  posts = "/blog/:slug/"

[outputFormats.RSS]
  baseName = "feed"
  mediaType = "application/rss+xml"
  isPLainText = true
