baseURL = 'https://cheztervargas.com/'
locale = "en"
title = "Chezter's Records"
uglyURLs = false
disableKinds = ["taxonomy", "term"]
ignoreFiles = ["notes\\.json$"]

[params]
  author = 'Chezter Vargas'

[permalinks]
  posts = "/blog/:slug/"
  notes = "/notes/:slug"
  
[outputFormats.RSS]
  baseName = "feed"
  mediaType = "application/rss+xml"
  isPlainText = true
